name: bulefin-trivalent

description: bluefin-dx-nvidia:stable-daily + trivalent (For my personal use and testing, DO NOT USE PLS)

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia

image-version: stable-daily

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
      - https://repo.secureblue.dev/secureblue.repo
    install:
      - trivalent

  - from-file: selinux-modules.yml

  - type: signing 
