---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bulefin-trivalent
description: bluefin-dx-nvidia:stable-daily + trivalent (For my personal use, DO NOT USE PLS)

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: stable-daily

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
      - https://repo.secureblue.dev/secureblue.repo
    install:
      - trivalent

  - type: signing 
